// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <cuda.h>
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/prctl.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <error.h>

static int syz_cuDeviceSetMemPool(int dev, CUmemoryPool pool)
{
  return cuDeviceSetMemPool(dev, pool);
}

static int syz_cuDeviceGetCount(int* count)
{
  return cuDeviceGetCount(count);
}

static int syz_cuDeviceGet(int* device, int ordinal)
{
  return cuDeviceGet(device, ordinal);
}

const int kExtraCoverSize = 256 << 10;
#define KCOV_ENABLE _IO('c', 100)
#define KCOV_INIT_TRACE64 _IOR('c', 1, uint64_t)

static void cover_enable()
{
        int fd = open("/sys/kernel/debug/kcov", O_RDWR);
        if (fd == -1)
                printf("open of /sys/kernel/debug/kcov failed\n");
        if (ioctl(fd, KCOV_INIT_TRACE64, kExtraCoverSize))
                perror("cover init trace write failed");
        unsigned int kcov_mode =  0;
        // The KCOV_ENABLE call should be fatal,
        // but in practice ioctl fails with assorted errors (9, 14, 25),
        // so we use exitf.
                if (ioctl(fd, KCOV_ENABLE, kcov_mode)) {
                        perror("cover enable write trace failed");
                }
                return;

}

static int syz_cuMemPoolCreate(CUmemoryPool* pool, CUmemPoolProps* poolProps)
{
  int ret = cuMemPoolCreate(pool, poolProps);
  printf("cuMemPoolCreate-> %d\n", ret);
  return ret;
}

static void setup_nvidia_driver()
{
  printf("setup cuInit\n");
  printf("cuInit-> %d\n", cuInit(0));
  return;
}

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  cover_enable();
  setup_nvidia_driver();

  CUmemPoolProps props = {0};
  props.allocType = CU_MEM_ALLOCATION_TYPE_PINNED;
  props.location.type = CU_MEM_LOCATION_TYPE_DEVICE;
  props.location.id = 0; // Device 0
  syz_cuMemPoolCreate(/*pool=*/0x20000040, /*props=*/&props);
  return 0;
}